version: '3'

services:
  prometheus:
    image: prom/prometheus
    volumes:
      - ./config:/prometheus
      - ./data/prometheus:/data
    command:
      - '--config.file=/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/data'
    ports:
      - 9090:9090
    depends_on:
      - alertmanager
    restart: always
    networks:
      - promnet

  alertmanager:
    image: prom/alertmanager
    volumes:
      - ./config:/prometheus
      - ./data/alertmanager:/data
    command:
      - '--config.file=/prometheus/alertmanager.yml'
      - '--storage.path=/data'
    ports:
      - 9093:9093
    networks:
      - promnet

  sut:
    image: alerta/alerta-web
    ports:
      - 8080
    depends_on:
      - db
    environment:
      # - DEBUG=1  # remove this line to turn DEBUG off
      - DATABASE_URL=postgres://postgres:postgres@db:5432/monitoring
      - AUTH_REQUIRED=True
      - ADMIN_USERS=admin@alerta.io,devops@alerta.io # default password: alerta
      - ADMIN_KEY=demo-key
      - ADMIN_KEY_MAXAGE=31536000 # 1 year in seconds
      - PLUGINS=reject,blackout,normalise,enhance
      networks:
        - promnet

  tester:
    image: tutum/curl:latest
    volumes:
      - ./wait-for-it.sh:/usr/local/bin/wait-for-it.sh
      - ./tests.sh:/tests.sh
    depends_on:
      - sut
    command: ["wait-for-it.sh", "sut:8080", "-t", "240", "--", "sh", "/tests.sh"]
    networks:
      - promnet

  db:
    image: postgres
    volumes:
      - ./pg-data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: monitoring
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    networks:
      - promnet
      